# Generated by Django 3.1.5 on 2021-01-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='page',
        ),
    ]
