version: '3.5'
services: 
    nginx:
        build: 
            context: .
            args:
                - NGINX_PORT=8084
        restart: always
        ports:
            - 8081:8084
        container_name: nginx-server
        volumes:
            - .:/app   
     