FROM python:3.7-slim
ENV PYTHONUNBUFFERED 1
RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python3.7", "sender.py"] 

#../venv/bin/watchmedo shell-command --patterns="*.py;*.txt"  --command='python3 sender.py'