# Generated by Django 3.1.5 on 2021-01-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.page')),
            ],
        ),
    ]
