# Generated by Django 3.1.5 on 2021-01-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_page_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default='1.png', upload_to='page_images'),
            preserve_default=False,
        ),
    ]
