# Generated by Django 3.1.5 on 2021-01-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_images_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='user_images')),
                ('sids', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
