# Generated by Django 3.1.5 on 2021-01-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gameuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
