# Generated by Django 3.1.5 on 2021-01-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20210128_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
