# Generated by Django 3.1.5 on 2021-01-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gameuser_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='sids',
            field=models.TextField(default=''),
        ),
    ]
