# Generated by Django 3.1.5 on 2021-01-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210128_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images')),
            ],
        ),
    ]
