# Generated by Django 3.1.5 on 2021-01-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_cards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
    ]
