# Generated by Django 3.1.5 on 2021-01-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_card2user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='state',
            field=models.CharField(choices=[('gessor', 'gessor'), ('gessed', 'gessed'), ('betor', 'betor'), ('beted', 'beted')], default='betor', max_length=10),
        ),
    ]
