# Generated by Django 3.1.5 on 2021-01-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_gameuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='account',
            field=models.IntegerField(default=0),
        ),
    ]
