# Generated by Django 3.1.5 on 2021-01-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='title',
            new_name='email',
        ),
    ]
