# Generated by Django 3.1.5 on 2021-01-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210123_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
