version: '2.0'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
      args:
        - NGINX_PORT=8084
    restart: always
    ports:
      - 8081:8084
    container_name: nginx_server
    volumes:
      - .:/app
    
  flask:
    build:
      context: .
      dockerfile: Dockerfile-python
    volumes:
      - .:/app
    command: python start.py